name: "Nix builds"

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        pyVersion:
          # - "39"
          - "310"
          # - "311"
          # - "312"
          # - "313"
        include:
          - system: x86_64-linux
            os: ubuntu-latest
          - system: x86_64-darwin
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          install_url: "https://releases.nixos.org/nix/nix-2.19.2/install"
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
            extra-platforms = x86_64-linux x86_64-darwin aarch64-darwin
            accept-flake-config = true
      - name: Install Rosetta
        if: ${{ contains(matrix.system, 'x86_64-darwin') }}
        run: sudo softwareupdate --install-rosetta --agree-to-license
      - name: Building package
        run: nix build ".#packages.${{ matrix.system }}.myapp-${{ matrix.pyVersion }}"
